services:
  mysql:
    image: mysql:8.0.2
    container_name: mysql-container
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${MYSQL_DOCKER_PORT}"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d

    networks:
      - app-network

  python-flask-app:
    build:
      context: ./python-flask-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    
    depends_on:
     - mysql
    
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
